server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    database: 5
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500

mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath*:mybatis/mapper/**/*.xml

#\u6253\u5370Mybatis\u65E5\u5FD7
logging:
  level:
    com.kangswx.springbootmybatisredis.mapper: debug
